@BASE_URL = http://localhost:5000
@JWT_TOKEN = YOUR_JWT_HERE  # Get this from the response after signing in
@USER_ID = YOUR_USER_ID_HERE  # Replace with your user ID from the database
@CHAT_USER_ID = CHAT_PARTNER_USER_ID_HERE  # Replace with the ID of the user you are chatting with




### Get all users for the sidebar (excluding logged-in user)
GET {{BASE_URL}}/api/message/users
Cookie: jwt={{JWT_TOKEN}}

### Get messages between logged-in user and another user
GET {{BASE_URL}}/api/message/{{CHAT_USER_ID}}
Cookie: jwt={{JWT_TOKEN}}

### Send a new text message
POST {{BASE_URL}}/api/message/send/{{CHAT_USER_ID}}
Content-Type: application/json
Cookie: jwt={{JWT_TOKEN}}

{
    "text": "Hello, how are you?"
}

### Send a new image message
POST {{BASE_URL}}/api/message/send/{{CHAT_USER_ID}}
Content-Type: application/json
Cookie: jwt={{JWT_TOKEN}}

{
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCRTXYXoGjgoZZSxVP2EwvTj8EXkSOlzJeDw&s"
}

